---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: macosx-10.10
    driver:
      box: roboticcheese/macosx-10.10
      ssh:
        insert_key: false
  - name: windows-8
    driver:
      box: roboticcheese/windows-8
  - name: ubuntu-14.04
  - name: debian-7.8

suites:
  - name: default
    run_list:
      - recipe[vlc]
    attributes:
  - name: uninstall
    run_list:
      - recipe[vlc_test::uninstall]
    attributes:
